### PR TITLE
sdm660: increase microphone sensitivity

### PR DESCRIPTION
**Pull request by jeangraff30**

### CODE REVIEW

**Comment by rcstar6696** [comment]
i will not merge that

**Comment by rcstar6696** [comment]
i will not increase mic gain in any way. mic gain matchs stock

**Comment by jeangraff30** [comment]
ok, base me on this mix patcher to get the correction, because i had a lot of complaints about mic, i'm not sure it's right
https://github.com/jeangraff30/vendor-miui/blob/db18d9745d900ab4f3b4a620538c52a6f881c843/etc/mixer_paths_wcd9340.xml#L357
actually the mixer patcher.xml corresponds to that of the tree, but I observed the others too, so I increased the sensitivity without losing the quality.

I'm sorry, I'm wrong

**Comment by rcstar6696** [comment]
what vendor is that ? https://github.com/jeangraff30/vendor-miui/blob/db18d9745d900ab4f3b4a620538c52a6f881c843/etc/mixer_paths_wcd9340.xml#L357

**Comment by jeangraff30** [comment]
MIUI Chineses V11.0.5.0.PDCCNXM | 9.0

**Pull request closed without merging**
